# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f16711df36c8fea9ad98bdaf061d5170b2a928c0ba642dd7ea61dc4449afb58239d12c890433b5b3de34932c4be73a1a58642ba8c1490bc409f4b29f825a961

test:
  secret_key_base: 1b94f6e2bc2d559503aa4b8dbe60d7597ad4e2c2d182f501ca4a69886c98aca97ad7aaf421780fc40734d1f51417d2fc80bdf776d493bcb92706e81db3a4e4aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
